---
output: html_document
---

```{r paths}
ppath <- '/Users/taylorminich/Documents/grad/mp/data/plots/'
ipath <- '/Users/taylorminich/Documents/grad/mp/images/'
rpath <- '/Users/taylorminich/Documents/grad/mp/results/'
tapath <- '/Users/taylorminich/Documents/grad/mp/data/ticks/abundance/'
mapath <- '/Users/taylorminich/Documents/grad/mp/data/mammals/abundance/'
spath <- '/Users/taylorminich/Documents/grad/mp/data/seeds/'

library(ggplot2)
library(ggmap)
library(ggrepel)
```

```{r periodic mast}
t <- seq(1, 15, 0.001)
mast <- ifelse(t < 4.243, cos(3*t)*sin(t)+1.5,
          ifelse(t >= 4.243 & t < 10.526, cos(t-.23033)*sin(2*t-1.1729)+1.172,
           ifelse(t>=10.526, cos(3*t)*sin(t)+1.5,0)))
mammalAnticipate <- ifelse(t < 4.243, cos(3*t)*sin(t)+1.5,
                      ifelse(t >= 4.243 & t < 10.526, cos(t-.23033)*sin(2*t-1.1729)+1.172,
                        ifelse(t>=10.526, cos(3*t)*sin(t)+1.5,0)))
mammalReact <- ifelse(t < 5.243, (1/2)*(sin(4*t-4)+sin(-2*t+2))+1.5,
                ifelse(t >= 5.243 & t < 11.526, (1/2)*(sin(3*t-4.40222)+sin(t-1.94268))+1.172,
                  ifelse(t>=11.526, (1/2)*(sin(4*t-4)+sin(-2*t+2))+1.5,0)))
df <- data.frame(t, mast, mammalAnticipate, mammalReact)

mast <- ggplot(data = df, aes(t, mast)) +
  geom_line() +
  geom_area(fill = '#004529', col = '#004529', alpha = 0.5) +
  scale_x_continuous(name ='year', labels = function(x) x+2000, breaks = pretty_breaks(n = 8)) +
  scale_y_continuous(name = 'mast production') +
  theme_minimal() +
  theme(axis.text.y = element_blank()) 

mammal <- ggplot(data = df) +
  geom_line(aes(t, mammalReact)) +
  geom_area(aes(t, mammalReact), fill = '#225ea8', col = '#225ea8', alpha = 0.3) +
  geom_line(aes(t, mammalAnticipate)) +
  geom_area(aes(t, mammalAnticipate), fill = '#225ea8', col = '#225ea8', alpha = 0.3) +
  scale_y_continuous(name = 'mammal abundance') +
  theme_minimal() +
  theme(axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank()) 

months <- c('J', 'A', 'S', 'O', 'N', 'D', 'J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D', 'J')

tick <- ggplot(data = data.frame(x = c(1, 19)), aes(x)) +
  geom_area(stat = 'function', fun = dnorm, args = list(mean = 2.5, sd = 0.5), fill = '#cc4c02', alpha = 0.5) +
  geom_area(stat = 'function', fun = dnorm, args = list(mean = 11.5, sd = 0.7), fill = '#cc4c02', alpha = 0.5) +
  geom_area(stat = 'function', fun = dnorm, args = list(mean = 17, sd = 0.8), fill = '#cc4c02', alpha = 0.5) +
  stat_function(fun = dnorm, n = 500, args = list(mean = 2.5, sd = 0.5), col = '#cc4c02') +
  stat_function(fun = dnorm, n = 500, args = list(mean = 11.5, sd = 0.7), col = '#cc4c02') +
  stat_function(fun = dnorm, n = 500, args = list(mean = 17, sd = 0.8), col = '#cc4c02') +
  scale_y_continuous(name = 'tick abundance') +
  scale_x_continuous(name ='month', labels = months, breaks = seq(1, 19, 1)) +
  theme_minimal() +
  theme(axis.text.y = element_blank(),
        axis.title.x = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) 

trophic <- grid.arrange(tick, mammal, mast, layout_matrix = rbind(c(NA, 1), c(2, 2), c(3, 3)))
ggsave(file = paste0(ipath, 'trophic.png'), trophic, device = NULL, width = 13.33, height = 7.5)
```

```{r site map}
mySites <- c('BART', 'BLAN', 'DSNY', 'GRSM', 'HARV', 'JERC', 'KONZ', 'ORNL', 'OSBS', 'SCBI', 'SERC', 'UKFS')
mastSites <- c('BART', 'BLAN','GRSM', 'HARV', 'SCBI', 'SERC')

sites <- read.csv(paste0(ppath, 'sites.csv')) %>%
  filter(Site.ID %in% mySites) %>%
  mutate(lat = as.numeric(substr(Lat..Long., 1, 7)), lon = as.numeric(substr(Lat..Long., 10, 18))) %>%
  select(Site.Name, Site.ID, lat, lon) %>%
  mutate(mastSite = as.factor(if_else(Site.ID %in% mastSites, 'mastif & neon', 'neon')))

loc <- c(lon = -83, lat = 37)
USAMap <- ggmap(get_map(loc, maptype = 'terrain', color = 'bw', zoom = 5, crop = FALSE, scale = 2, size = c(640, 360)))

siteMap <- USAMap + 
  geom_point(data = sites, aes(x = lon, y = lat, col = mastSite), size = 2) +
  geom_point(data = sites, aes(x = lon, y = lat), shape = 1, size = 2.5, colour = 'darkgrey') +
  geom_label_repel(data = sites,
    aes(x = lon, y = lat, label = Site.Name), 
    size = 2.5, 
    box.padding = 0.2, point.padding = 0.3,
    segment.color = 'grey50')  +
  scale_color_manual('site type', values=c('#dfc27d', '#4393c3')) +
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = unit(c(0, 0, -1, -1), 'lines'),
        legend.justification = c(1, 0.05), 
        legend.position = c(1, 0.05),
        legend.background = element_rect(fill = alpha('white', 0.9))) +
  xlab('') +
  ylab('')

ggsave(file = paste0(ipath, 'siteMap.png'), siteMap, device = NULL)
```

```{r example plots}
mplotGRSM <- c('GRSM_013', 'GRSM_070', 'GRSM_014', 'GRSM_069', 'GRSM_071', 'GRSM_003', 'GRSM_015')
tplotGRSM <- c('GRSM_006', 'GRSM_004', 'GRSM_010', 'GRSM_009', 'GRSM_005', 'GRSM_003', 'GRSM_015')
pplotGRSM <- c('GRSM_013', 'GRSM_004', 'GRSM_014', 'GRSM_008', 'GRSM_011', 'GRSM_003', 'GRSM_015')

pairs <- data.frame(mplotGRSM, tplotGRSM, pplotGRSM)
colnames(pairs) <- c('mammal', 'tick', 'plant')

pairs <- pairs %>%
   mutate(mammalTick = paste(mammal, tick, sep = '_'), plantMammal = paste(plant, mammal, sep = '_'))

tickPlots <- read.csv(paste0(tapath, 'tick.csv')) %>%
  select(plotID, lat, lon) %>%
  filter(plotID %in% pairs$tick) %>%
  distinct() %>%
  mutate(type = 'tick')

mammalPlots <- read.csv(paste0(mapath, 'mammal.csv')) %>%
  select(plotID, lat, lon) %>%
  filter(plotID %in% pairs$mammal) %>%
  distinct() %>%
  mutate(type = 'small mammal')

plantPlots <- read.csv(paste0(ppath, 'allPlots.csv')) %>%
  rename(lat = latitude, lon = longitude) %>%
  select(plotID, lat, lon) %>%
  filter(plotID %in% pairs$plant) %>%
  group_by(plotID) %>%
  summarise(lat = mean(lat), lon = mean(lon)) %>%
  mutate(type = 'tree')

df <- data.frame(bind_rows(plantPlots, mammalPlots, tickPlots))

mammalTickPlots <- bind_rows(mammalPlots, tickPlots) %>%
  distinct() %>%
  left_join(pairs, by = c('plotID' = 'mammal')) %>%
  select(plotID, lat, lon, mammalTick) %>%
  left_join(pairs, by = c('plotID' = 'tick')) %>%
  mutate(mammalTick = coalesce(mammalTick.x, mammalTick.y)) %>%
  select(plotID, lat, lon, mammalTick)

plantMammalPlots <- bind_rows(plantPlots, mammalPlots) %>%
  distinct() %>%
  left_join(pairs, by = c('plotID' = 'plant')) %>%
  select(plotID, lat, lon, plantMammal) %>%
  left_join(pairs, by = c('plotID' = 'mammal')) %>%
  mutate(plantMammal = coalesce(plantMammal.x, plantMammal.y)) %>%
  select(plotID, lat, lon, plantMammal)
  

loc <- c(lon = -83.47, lat = 35.68)
GRSMMap <- ggmap(get_map(loc, maptype = 'terrain', color = 'bw', zoom = 12, crop = FALSE, scale = 2, size = c(640, 360)))

plotMap <- GRSMMap + 
  geom_point(data = df, aes(x = lon, y = lat, col = type), size = 3.5, alpha = 1) +
  geom_line(data = mammalTickPlots, aes(x = lon, y = lat, group = mammalTick), col = '#525252') +
  geom_line(data = plantMammalPlots, aes(x = lon, y = lat, group = plantMammal), col = '#525252') +
  scale_color_manual('plot type', values=c('#225ea8', '#cc4c02', '#004529')) +
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = unit(c(0, 0, -1, -1), 'lines'),
        legend.justification = c(1, 0.05), 
        legend.position = c(1, 0.05),
        legend.background = element_rect(fill = alpha('white', 0.9))) +
  xlab('') +
  ylab('')

ggsave(file = paste0(ipath, 'plotMap.png'), plotMap, device = NULL)
```

```{r plant-mammal lag model}
load(paste0(rpath, 'pmTotalLag2Output.rdata'))

cred <- pmTotalLag2Output$parameters$betaStandXWTable %>%
  rownames_to_column %>%
  separate(rowname, c('species','predictor'), sep = '_') %>%
  mutate(species = factor(species))  %>%
  mutate(predictor = factor(predictor, levels = c('t', 't1'))) %>%
  mutate(relationship = if_else(Estimate < 0, 'negative', 'positive')) %>%
  mutate(predictor = recode_factor(predictor, `t` = 't', `t1` = 't - 1'))

cred$labs <- factor(cred$species, labels = c(
           `BLBR` = expression(atop('Northern short-tailed shrew', italic('(Blarina brevicauda)'))), 
           `PELE` = expression(atop('White-footed mouse', italic('(Peromyscus leucopus)'))), 
           `PEMA` = expression(atop('Deer mouse', italic('(Peromyscus maniculatus)'))), 
           `SOCI` = expression(atop('Common shrew', italic('(Sorex cinereus)'))), 
           `TAST` = expression(atop('Eastern chipmunk', italic('(Tamias striatus)')))))


pmLag <- ggplot(cred, aes(x = predictor, y = Estimate, col = relationship)) +
  geom_point() +
  facet_grid(vars(labs), labeller = label_parsed) +
  scale_y_continuous(breaks = seq(-5, 5, 5), limits = c(-8.5, 8.5)) +
  geom_errorbar(aes(ymin = CI_025, ymax = CI_975), width = 0.1) +
  scale_color_manual(values=c("#E69F00", "#56B4E9")) +
  xlab('') +
  theme_minimal() +
  theme(legend.position = 'bottom', 
        strip.text.y = element_text(angle = 0),
        panel.spacing.y = unit(0.5, 'lines'),
        axis.text.x = element_text(size = 12), 
        text = element_text(size = 12))

ggsave(file = paste0(ipath, 'pmLag.png'), pmLag, device = NULL, width = 7.5, height = 7.5)
```

```{r plant-mammal genera model}
load(paste0(rpath, 'pmHostTOutput.rdata'))
load(paste0(rpath, 'pmHostT1Output.rdata'))

pmHostT <- data.frame(pmHostTOutput$parameters$betaStandXWTable) %>%
  rownames_to_column %>%
  separate(rowname, c('species', 'predictor'), sep = '_')

pmHostT1 <- data.frame(pmHostT1Output$parameters$betaStandXWTable) %>%
  rownames_to_column %>%
  separate(rowname, c('species', 'predictor'), sep = '_')

cred <- pmHostT %>%
  bind_rows(pmHostT1) %>%
  mutate(bottom = if_else(CI_025 < 0, -1, 1), top = if_else(CI_975 < 0, -1, 1)) %>%
  mutate(sig = bottom + top) %>%
  mutate(significance = as.factor(case_when(sig == -2 ~ 'negative relationship',
                                  sig == 0 ~ 'non-significant',
                                  sig == 2 ~ 'positive relationship'))) %>%
  select(-sig, -bottom, -top) %>%
  mutate(predictor = factor(predictor)) 


cred$pred <- factor(cred$predictor, labels = c( `Acer` = expression(paste('Maple ', italic('(Acer)'))),
                                   `Betula` = expression(paste('Birch ', italic('(Betula)'))),
                                   `Carya` = expression(paste('Hickory ', italic('(Carya)'))),
                                   `Cornus` = expression(paste('Dogwood ', italic('(Cornus)'))),
                                   `Fagus` = expression(paste('Beech ', italic('(Fagus)'))),
                                   `Fraxinus` = expression(paste('Ash ', italic('(Fraxinus)'))),
                                   `Ilex` = expression(paste('Holly ', italic('(Ilex)'))),
                                   `Liquidambar` = expression(paste('Sweet gum ', italic('(Liquidambar)'))),
                                   `Nyssa` = expression(paste('Black gum ', italic('(Nyssa)'))),
                                   `Picea` = expression(paste('Spruce ', italic('(Picea)'))),
                                   `Pinus` = expression(paste('Pine ', italic('(Pinus)'))),
                                   `Quercus` = expression(paste('Oak ', italic('(Quercus)'))),
                                   `Tsuga` = expression(paste('Hemlock ', italic('(Tsuga)')))))

cred$labs <- factor(cred$species, labels = c(
           `BLBR` = expression(atop('Northern short-tailed shrew', italic('(Blarina brevicauda)'))), 
           `PELE` = expression(atop('White-footed mouse', italic('(Peromyscus leucopus)'))), 
           `PEMA` = expression(atop('Deer mouse', italic('(Peromyscus maniculatus)'))), 
           `SOCI` = expression(atop('Common shrew', italic('(Sorex cinereus)'))), 
           `TAST` = expression(atop('Eastern chipmunk', italic('(Tamias striatus)')))))

pmGenera <- ggplot(cred, aes(x = pred, y = Estimate, col = significance)) + 
  geom_point() +
  facet_grid(vars(labs), labeller = label_parsed) +
  geom_errorbar(aes(ymin = CI_025, ymax = CI_975), width = 0.1) +
  scale_color_manual(values=c("#E69F00", "#999999", "#56B4E9")) +
  scale_y_continuous(breaks = seq(-2, 2, 2), limits = c(-4, 4)) +
  xlab('') +
  theme_minimal() +
  scale_x_discrete(labels = function(l) parse(text = l)) +
  theme(legend.position = 'bottom', 
        axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
        panel.spacing.y = unit(0.2, 'lines'),
        strip.text.y = element_text(angle = 0),
        text = element_text(size = 13))

ggsave(file = paste0(ipath, 'pmGenera.png'), pmGenera, device = NULL, width = 7.5, height = 7.5)
```

```{r mammal-tick lag model}
load(paste0(rpath, 'mtTotalLag2Output.rdata'))

cred <- mtTotalLag2Output$parameters$betaStandXWTable %>%
  rownames_to_column %>%
  separate(rowname, c('tick','predictor'), sep = '_') %>%
  mutate(tick = factor(tick, levels = c('larvaCount', 'nymphCount', 'adultCount'))) %>%
  mutate(predictor = factor(predictor, levels = c('t', 't1'))) %>%
  mutate(bottom = if_else(CI_025 < 0, -1, 1), top = if_else(CI_975 < 0, -1, 1)) %>%
  mutate(sig = bottom + top) %>%
  mutate(significance = as.factor(case_when(sig == -2 ~ 'negative relationship',
                                  sig == 0 ~ 'non-significant',
                                  sig == 2 ~ 'positive relationship'))) %>%
  mutate(predictor = recode_factor(predictor, `t` = 't', `t1` = 't - 1')) %>%
  select(-sig, -bottom, -top)

tickLab <- c(`adultCount` = 'adult stage',
             `larvaCount` = 'larva stage',
             `nymphCount` = 'nymph stage')

mtLag <- ggplot(cred, aes(x = predictor, y = Estimate, col = significance)) + 
  geom_point() +
  facet_grid(vars(tick), labeller = labeller(tick = tickLab)) +
  scale_y_continuous(breaks = seq(-0.5, 0.5, 0.5), limits = c(-0.5, 0.5)) +
  geom_errorbar(aes(ymin = CI_025, ymax = CI_975), width = 0.1) +
  scale_color_manual(values=c("#999999", "#56B4E9")) +
  xlab('') +
  theme_minimal() +
  theme(legend.position = 'bottom',
        strip.text.y = element_text(angle = 0),
        panel.spacing.y = unit(2, 'lines'),
        axis.text.x = element_text(size = 15),
        text = element_text(size = 15))


ggsave(file = paste0(ipath, 'mtLag.png'), mtLag, device = NULL, width = 7.5, height = 7.5)
```

```{r mammal-tick species model with reduced species from host genera}
load(paste0(rpath, 'mtHostOutput.rdata'))

cred <- mtHostOutput$parameters$betaStandXWTable %>%
  rownames_to_column %>%
  separate(rowname, c('tick','predictor'), sep = '_') %>%
  mutate(tick = factor(tick, levels = c('larvaCount', 'nymphCount', 'adultCount'))) %>%
  mutate(species = predictor) %>%
  select(-predictor) %>%
  mutate(bottom = if_else(CI_025 < 0, -1, 1), top = if_else(CI_975 < 0, -1, 1)) %>%
  mutate(sig = bottom + top) %>%
  mutate(significance = as.factor(case_when(sig == -2 ~ 'negative relationship',
                                  sig == 0 ~ 'non-significant',
                                  sig == 2 ~ 'positive relationship'))) %>%
  select(-sig, -bottom, -top) 

cred$pred <- factor(cred$species, labels = c(
           `BLBR` = expression(atop('Northern short-tailed shrew', italic('(Blarina brevicauda)'))), 
           `BLCA` = expression(atop('Southern short-tailed shrew', italic('(Blarina carolinensis)'))),
           `BLHY` = expression(atop("Elliot's short-tailed shrew", italic('(Blarina hylophaga)'))),
           `PELE` = expression(atop('White-footed mouse', italic('(Peromyscus leucopus)'))),
           `PEMA` = expression(atop('Deer mouse', italic('(Peromyscus maniculatus)'))), 
           `PEME` = expression(atop('Mesquite mouse', italic('(Peromyscus merriami)'))),
           `SOCI` = expression(atop('Common shrew', italic('(Sorex cinereus)'))), 
           `TAST` = expression(atop('Eastern chipmunk', italic('(Tamias striatus)')))))

tickLab <- c(`adultCount` = 'adult stage',
             `larvaCount` = 'larva stage',
             `nymphCount` = 'nymph stage')

mtSpecies <- ggplot(cred, aes(x = pred, y = Estimate, col = significance)) + 
  geom_point() +
  facet_grid(vars(tick), labeller = labeller(tick = tickLab)) +
  geom_errorbar(aes(ymin = CI_025, ymax = CI_975), width = 0.1) +
  scale_color_manual(values=c("#E69F00", "#999999", "#56B4E9")) +
  scale_x_discrete(labels = function(l) parse(text = l)) +
  scale_y_continuous(breaks = seq(-0.5, 0.5, 0.5), limits = c(-0.65, 0.65)) +
  xlab('') +
  theme_minimal() +
  theme(legend.position = 'bottom', 
        axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
        panel.spacing.y = unit(2, 'lines'),
        strip.text.y = element_text(angle = 0),
        text = element_text(size = 15))

ggsave(file = paste0(ipath, 'mtSpecies.png'), mtSpecies, device = NULL, width = 9, height = 7.5)
```

```{r phylogeny}
genera <- read.tree(text = '(((((((Fraxinus_-_ash, Ilex_-_holly), Oxydendrum_-_sourwood)), 
                  (Cornus_-_dogwood, Nyssa_-_black_gum)), ((((Fagus_-_beech, Quercus_-_oak), Carya_-_hickory), 
                  Betula_-_birch), Acer_-_maple)), Liquidambar_-_sweet_gum), ((Pinus_-_pine, Picea_-_spruce), Tsuga_-_hemlock));')
plot(genera, edge.width = 1)

png(file = '/Users/taylorminich/Documents/grad/mp/images/genera.png', width = 650, height = 650)
plot(genera, edge.width = 1)
dev.off()

species <- read.tree(text = '((((Blarina_brevicauda_-_northern_short-tailed_shrew, Blarina_carolinensis_-_southern_short-tailed_shrew), Blarina_hylophaga_-_Elliot`s_short-tailed_shrew), Sorex_cinereus_-_common_shrew), (((Peromyscus_maniculatus_-_deer_mouse, Peromyscus_leucopus_-_white-footed_mouse), Peromyscus_merriami_-_mesquite_mouse), Tamias_striatus_-_eastern_chipmunk));')
plot(species, edge.width = 1)

png(file = '/Users/taylorminich/Documents/grad/mp/images/species.png', width = 650, height = 650)
plot(species, edge.width = 1)
dev.off()
```

```{r data visualization}
nutrition <- read.csv(paste0(spath, 'nutrition.csv'))
mast <- read.csv(paste0(spath, 'mast.csv')) 

plant <- nutrition %>%
  left_join(mast, by = c('code', 'genus')) %>%
  filter(year > 2012) %>%
  mutate(year = ymd(paste0(year, '-01-01'))) %>%
  mutate(grams = mast*gmPerSeed) %>%
  filter(grams < 100000) %>%
  group_by(siteID) %>%
  mutate(abundance = (grams-min(grams))/(max(grams)-min(grams)))
  

mammal <- read.csv(paste0(mapath, 'mammal.csv')) %>%
    select(collectDate, siteID, total, totalTraps) %>%
    mutate(collectDate = ymd(collectDate)) %>%
    mutate(tmp = total/totalTraps) %>%
    group_by(siteID) %>%
    mutate(abundance = (tmp-min(tmp))/(max(tmp)-min(tmp))) %>%
    select(collectDate, siteID, total, totalTraps, abundance)

tick <- read.csv(paste0(tapath, 'tick.csv')) %>%
    select(collectDate, siteID, totalCount, totalSampledArea) %>%
    mutate(collectDate = ymd(collectDate)) %>%
    mutate(tmp = totalCount/totalSampledArea) %>%
    group_by(siteID) %>%
    mutate(abundance = (tmp-min(tmp))/(max(tmp)-min(tmp))) %>%
    select(collectDate, siteID, totalCount, totalSampledArea, abundance)


ggplot(data = NULL) +
      geom_point(data = plant, aes(x = year, y = abundance, colour = 'mast'), alpha = 0.3) +
      geom_point(data = mammal, aes(x = collectDate, y = abundance, colour = 'mammal'), alpha = 0.3) +
      geom_point(data = tick, aes(x = collectDate, y = abundance, colour = 'tick'), alpha = 0.3) +
      facet_wrap(vars(siteID), ncol = 3) +
      geom_line(data = plant, aes(x = year, y = abundance, colour = 'mast'), stat = 'smooth', method = 'loess', alpha = 0.9) +
      geom_line(data = mammal, aes(x = collectDate, y = abundance, colour = 'mammal'), stat="smooth", method = "loess", alpha = 0.9) +
      geom_line(data = tick, aes(x = collectDate, y = abundance, colour = 'tick'), 
                stat="smooth",method = "loess", alpha = 0.9) +
      scale_y_continuous(limits = c(0, 1)) +
      xlab('Collection date') +
      ylab('Relative abundance') +
      scale_colour_manual(name = '', values = c(mast = '#004529', mammal = '#225ea8', tick = '#cc4c02')) +
      theme_minimal() +
      theme(legend.position = 'bottom')

ggplot(data = NULL) +
      geom_point(data = plant, aes(x = year, y = abundance, colour = 'mast'), alpha = 0.3) +
      facet_wrap(vars(siteID), ncol = 3) +
      geom_line(data = plant, aes(x = year, y = abundance, colour = 'mast'), stat = 'smooth', method = 'loess', alpha = 0.9)
```

```{r concluding lag} 
t <- seq(0, 5, 0.01)
mast <- -cos(t-1)*sin(2*t)+1.2

mammalReact <- data.frame(-cos(t-1)*sin(2*t)+1.2)
colnames(mammalReact) <- 'mammalReact'

mammalAnticipate <- data.frame((-1/2)*(sin(3*t-1+3) + sin(t+1+1))+1.2)
colnames(mammalAnticipate) <- 'mammalAnticipate'

tickReact <- data.frame((-1/2)*(sin(3*t-1+3) + sin(t+1+1))+1.2)
colnames(tickReact) <- 'tickReact'

tickAnticipate <- data.frame(-cos(t-1)*sin(2*t)+1.2)
colnames(tickAnticipate) <- 'tickAnticipate'

df <- data.frame(t, mast, mammalReact, mammalAnticipate, tickReact, tickAnticipate) 

mastReact <- ggplot(data = df, aes(t, mast)) +
  geom_line() +
  geom_area(fill = '#004529', col = '#004529', alpha = 0.5) +
  scale_x_continuous(name ='year', labels = function(x) x+2000, breaks = pretty_breaks(n = 5)) +
  scale_y_continuous(name = 'mast production') +
  theme_minimal() +
  theme(axis.text.y = element_blank()) 

mastAnticipate <- ggplot(data = df, aes(t, mast)) +
  geom_line() +
  geom_area(fill = '#004529', col = '#004529', alpha = 0.5) +
  scale_x_continuous(name ='year', labels = function(x) x+2000, breaks = pretty_breaks(n = 5)) +
  ylab('') +
  theme_minimal() +
  theme(axis.text.y = element_blank()) 

mammalReact <- ggplot(data = df) +
  geom_line(aes(t, mammalReact)) +
  geom_area(aes(t, mammalReact), fill = '#225ea8', col = '#225ea8', alpha = 0.3) +
  scale_y_continuous(name = 'mammal abundance') +
  theme_minimal() +
  theme(axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank()) 

mammalAnticipate <- ggplot(data = df) +
  geom_line(aes(t, mammalAnticipate)) +
  geom_area(aes(t, mammalAnticipate), fill = '#225ea8', col = '#225ea8', alpha = 0.3) +
  theme_minimal() +
  ylab('') +
  theme(axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank()) 

tickReact <- ggplot(data = df) +
  geom_line(aes(t, tickReact)) +
  geom_area(aes(t, tickReact), fill = '#cc4c02', col = '#cc4c02', alpha = 0.3) +
  scale_y_continuous(name = 'tick abundance') +
  theme_minimal() +
  theme(axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank()) 

tickAnticipate <- ggplot(data = df) +
  geom_line(aes(t, tickAnticipate)) +
  geom_area(aes(t, tickAnticipate), fill = '#cc4c02', col = '#cc4c02', alpha = 0.3) +
  theme_minimal() +
  ylab('') +
  theme(axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank()) 

lag <- grid.arrange(tickReact, tickAnticipate, mammalReact, mammalAnticipate, mastReact, mastAnticipate, layout_matrix = rbind(c(1, 2), c(3, 4), c(5, 6)))
ggsave(file = paste0(ipath, 'lag.png'), lag, device = NULL, width = 7.5, height = 7.5)
```